import "../../appFont.css";
import "../../globals.css";
import type { Metadata } from "next";
import { Providers } from "@/utils/providers";
import { Toaster } from "@jua/ui/toaster";
import { setDefaultOptions } from "date-fns";
import { ptBR } from "date-fns/locale";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  setDefaultOptions({ locale: ptBR });

  return (
    <html lang="pt-br" className="font-roboto">
      <body>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
