version: '3.9'

services:
  database:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=app
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - fleet_net

networks:
  fleet_net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
